# TCL File Generated by Component Editor 18.1
# Thu May 16 15:01:23 CEST 2024
# DO NOT MODIFY


# 
# firefly_xcvr_ctrl "Firefly Tranceiver I2C Controller" v1.9.6
# Yifeng Wang 2024.05.16.15:01:23
# Interfacing with two Samtec FireFly ECUO 14G x4 optical modules. Function as the I2C master to monitor the temperature, vcc and rx power of the modules.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module firefly_xcvr_ctrl
# 
set_module_property DESCRIPTION "Interfacing with two Samtec FireFly ECUO 14G x4 optical modules. Function as the I2C master to monitor the temperature, vcc and rx power of the modules."
set_module_property NAME firefly_xcvr_ctrl
set_module_property VERSION 1.9.6
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Control Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property DISPLAY_NAME "Firefly Tranceiver I2C Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL firefly_xcvr_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file firefly_constants.vhd VHDL PATH firefly_constants.vhd
add_fileset_file firefly_i2c.vhd VHDL PATH firefly_i2c.vhd
add_fileset_file firefly_xcvr_ctrl.vhd VHDL PATH firefly_xcvr_ctrl.vhd TOP_LEVEL_FILE
add_fileset_file i2c_master.vhd VHDL PATH i2c_master.vhd


# 
# documentation links
# 
add_documentation_link "FireFly ECUO 14Gbps x 4" https://www.physi.uni-heidelberg.de/Forschung/he/mu3e/restricted/notes/Mu3e-Note-0040-FireflyTransceiver_B04.pdf


# 
# parameters
# 
add_parameter I2C_BAUD_RATE NATURAL 400000
set_parameter_property I2C_BAUD_RATE DEFAULT_VALUE 400000
set_parameter_property I2C_BAUD_RATE DISPLAY_NAME I2C_BAUD_RATE
set_parameter_property I2C_BAUD_RATE TYPE NATURAL
set_parameter_property I2C_BAUD_RATE UNITS None
set_parameter_property I2C_BAUD_RATE ALLOWED_RANGES 0:2147483647
set_parameter_property I2C_BAUD_RATE HDL_PARAMETER true
add_parameter SYSTEM_CLK_FREQ NATURAL 156250000
set_parameter_property SYSTEM_CLK_FREQ DEFAULT_VALUE 156250000
set_parameter_property SYSTEM_CLK_FREQ DISPLAY_NAME SYSTEM_CLK_FREQ
set_parameter_property SYSTEM_CLK_FREQ TYPE NATURAL
set_parameter_property SYSTEM_CLK_FREQ UNITS None
set_parameter_property SYSTEM_CLK_FREQ ALLOWED_RANGES 0:2147483647
set_parameter_property SYSTEM_CLK_FREQ HDL_PARAMETER true
add_parameter AVS_FIREFLY_ADDR_W NATURAL 5
set_parameter_property AVS_FIREFLY_ADDR_W DEFAULT_VALUE 5
set_parameter_property AVS_FIREFLY_ADDR_W DISPLAY_NAME AVS_FIREFLY_ADDR_W
set_parameter_property AVS_FIREFLY_ADDR_W TYPE NATURAL
set_parameter_property AVS_FIREFLY_ADDR_W UNITS None
set_parameter_property AVS_FIREFLY_ADDR_W ALLOWED_RANGES 0:2147483647
set_parameter_property AVS_FIREFLY_ADDR_W HDL_PARAMETER true
add_parameter DEBUG NATURAL 1
set_parameter_property DEBUG DEFAULT_VALUE 1
set_parameter_property DEBUG DISPLAY_NAME DEBUG
set_parameter_property DEBUG TYPE NATURAL
set_parameter_property DEBUG ENABLED false
set_parameter_property DEBUG UNITS None
set_parameter_property DEBUG ALLOWED_RANGES 0:2147483647
set_parameter_property DEBUG HDL_PARAMETER true


# 
# display items
# 


# 
# connection point firefly
# 
add_interface firefly avalon end
set_interface_property firefly addressUnits WORDS
set_interface_property firefly associatedClock system_clock
set_interface_property firefly associatedReset system_reset
set_interface_property firefly bitsPerSymbol 8
set_interface_property firefly burstOnBurstBoundariesOnly false
set_interface_property firefly burstcountUnits WORDS
set_interface_property firefly explicitAddressSpan 0
set_interface_property firefly holdTime 0
set_interface_property firefly linewrapBursts false
set_interface_property firefly maximumPendingReadTransactions 0
set_interface_property firefly maximumPendingWriteTransactions 0
set_interface_property firefly readLatency 0
set_interface_property firefly readWaitTime 1
set_interface_property firefly setupTime 0
set_interface_property firefly timingUnits Cycles
set_interface_property firefly writeWaitTime 0
set_interface_property firefly ENABLED true
set_interface_property firefly EXPORT_OF ""
set_interface_property firefly PORT_NAME_MAP ""
set_interface_property firefly CMSIS_SVD_VARIABLES ""
set_interface_property firefly SVD_ADDRESS_GROUP ""

add_interface_port firefly avs_firefly_address address Input avs_firefly_addr_w
add_interface_port firefly avs_firefly_read read Input 1
add_interface_port firefly avs_firefly_write write Input 1
add_interface_port firefly avs_firefly_readdata readdata Output 32
add_interface_port firefly avs_firefly_writedata writedata Input 32
add_interface_port firefly avs_firefly_waitrequest waitrequest Output 1
set_interface_assignment firefly embeddedsw.configuration.isFlash 0
set_interface_assignment firefly embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment firefly embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment firefly embeddedsw.configuration.isPrintableDevice 0


# 
# connection point system_clock
# 
add_interface system_clock clock end
set_interface_property system_clock clockRate 156250000
set_interface_property system_clock ENABLED true
set_interface_property system_clock EXPORT_OF ""
set_interface_property system_clock PORT_NAME_MAP ""
set_interface_property system_clock CMSIS_SVD_VARIABLES ""
set_interface_property system_clock SVD_ADDRESS_GROUP ""

add_interface_port system_clock i_clk clk Input 1


# 
# connection point system_reset
# 
add_interface system_reset reset end
set_interface_property system_reset associatedClock system_clock
set_interface_property system_reset synchronousEdges DEASSERT
set_interface_property system_reset ENABLED true
set_interface_property system_reset EXPORT_OF ""
set_interface_property system_reset PORT_NAME_MAP ""
set_interface_property system_reset CMSIS_SVD_VARIABLES ""
set_interface_property system_reset SVD_ADDRESS_GROUP ""

add_interface_port system_reset i_rst reset Input 1


# 
# connection point to_firefly_ucc8
# 
add_interface to_firefly_ucc8 conduit end
set_interface_property to_firefly_ucc8 associatedClock ""
set_interface_property to_firefly_ucc8 associatedReset ""
set_interface_property to_firefly_ucc8 ENABLED true
set_interface_property to_firefly_ucc8 EXPORT_OF ""
set_interface_property to_firefly_ucc8 PORT_NAME_MAP ""
set_interface_property to_firefly_ucc8 CMSIS_SVD_VARIABLES ""
set_interface_property to_firefly_ucc8 SVD_ADDRESS_GROUP ""

add_interface_port to_firefly_ucc8 io_firefly_scl scl Bidir 1
add_interface_port to_firefly_ucc8 i_firefly_present_n present_n Input 2
add_interface_port to_firefly_ucc8 io_firefly_sda sda Bidir 1
add_interface_port to_firefly_ucc8 o_firefly_reset_n reset_n Output 2
add_interface_port to_firefly_ucc8 o_firefly_select_n select_n Output 2
add_interface_port to_firefly_ucc8 i_firefly_int_n int_n Input 2

